In [2]:
import pandas as pd
import numpy as np

In [3]:
dataset=pd.read_csv("Fish.csv")

In [4]:
dataset.head()

Species  Length1  Length2  Length3   Height   Width  Weight
0   Bream     23.2     25.4     30.0  11.5200  4.0200   242.0
1   Bream     24.0     26.3     31.2  12.4800  4.3056   290.0
2   Bream     23.9     26.5     31.1  12.3778  4.6961   340.0
3   Bream     26.3     29.0     33.5  12.7300  4.4555   363.0
4   Bream     26.5     29.0     34.0  12.4440  5.1340   430.0

In [5]:
dataset.isnull().any()

Species    False
Length1    False
Length2    False
Length3    False
Height     False
Width      False
Weight     False
dtype: bool

In [6]:
x=dataset.iloc[:,0:6]
x.head()

Species  Length1  Length2  Length3   Height   Width
0   Bream     23.2     25.4     30.0  11.5200  4.0200
1   Bream     24.0     26.3     31.2  12.4800  4.3056
2   Bream     23.9     26.5     31.1  12.3778  4.6961
3   Bream     26.3     29.0     33.5  12.7300  4.4555
4   Bream     26.5     29.0     34.0  12.4440  5.1340

In [7]:
y=dataset.iloc[:,6]
y.head()

0    242.0
1    290.0
2    340.0
3    363.0
4    430.0
Name: Weight, dtype: float64

In [8]:
dataset['Species'].unique()

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [9]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer([("oh",OneHotEncoder(),[0])],remainder="passthrough")
x=ct.fit_transform(x)

In [22]:
x.shape


(159, 12)

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=402)

In [12]:
from sklearn.linear_model import LinearRegression
mlr=LinearRegression()
mlr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [13]:
ypred=mlr.predict(x_test)

In [14]:
ypred

array([ 8.68448491e+02,  6.83772267e+02,  7.20497364e+01,  1.92234262e+02,
        3.72342711e+02,  9.51598149e+02,  8.70426240e+02,  3.04112236e+01,
        8.08536424e+02,  1.77607087e+02,  3.86385905e+00,  9.98860358e+02,
        1.23216161e+02,  3.48073202e+01,  3.43741023e+02,  2.13501560e+02,
        7.39419352e+02,  3.72411053e+02,  6.62652456e+02,  6.07327535e+02,
        1.43055765e+03,  6.53243012e+02,  9.34358748e+02,  8.63107850e+02,
        2.12545261e-01,  2.02903222e+02,  5.30037629e+02,  1.48825435e+02,
        1.93052746e+02, -1.46212171e+01,  2.04467562e+02,  4.41587914e+02])

In [15]:
from sklearn.metrics import r2_score
acc=r2_score(ypred,y_test)

In [16]:
acc

0.9562214516663954

In [17]:
mlr.predict(ct.transform(dataset.head(5)))

array([290.44363295, 343.74102321, 352.18775573, 441.58791405,
       438.07846381])

In [18]:
dataset.head()

Species  Length1  Length2  Length3   Height   Width  Weight
0   Bream     23.2     25.4     30.0  11.5200  4.0200   242.0
1   Bream     24.0     26.3     31.2  12.4800  4.3056   290.0
2   Bream     23.9     26.5     31.1  12.3778  4.6961   340.0
3   Bream     26.3     29.0     33.5  12.7300  4.4555   363.0
4   Bream     26.5     29.0     34.0  12.4440  5.1340   430.0

In [19]:
b=ct.transform([["Bream",24,56.3,32.6,98,34]])

In [20]:
b

array([[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 24, 56.3, 32.6, 98, 34]],
      dtype=object)

In [163]:
mlr.predict(b)

array([2603.01956224])